name: ErrorAction

on:
  workflow_run:
    workflows:
    - PR Prettier
    types: [ completed ]

jobs:
  comment-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.1
      with:
      api-token: ${{ github.token }}
