name: PR Prettier

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  perttire-job:
    name: perttire job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        
      - name: Run Prettier
        id: prettier
        run: npx prettier -c $(find|grep -e ".*\.js$"|grep -v "./node_modules")

      - name: Post error message to PR
        if: steps.prettier.outcome == 'failure'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const errorMessage = 'Prettier formatting failed. Please check your code.';
            const { owner, repo, number } = context.issue;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            octokit.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: number,
              body: errorMessage
            });
